package:
  name: tensor_comprehensions
  version: "{{ environ.get('TC_BUILD_VERSION') }}"

source:
  git_url: https://github.com/nicolasvasilache/c2isl.git
  git_rev: "{{ environ.get('TC_GIT_HASH') }}"

requirements:
  build:
    - isl-tc==0.2.1
    - llvm==0.2.1
    - halide==0.2.1
    - gflags==2.4.4
    - glog==0.3.9
    - protobuf==3.4.1
    # we install pytorch since we want compatibility of TC with it for the release
    - pytorch==0.3.1
    - gmp>=5.0.1,<7
    - cmake
    - setuptools
    - pyyaml
    - cudatoolkit

  run:
    - isl-tc==0.2.1
    - llvm==0.2.1
    - halide==0.2.1
    - gflags==2.4.4
    - glog==0.3.9
    - protobuf==3.4.1
    - pytorch==0.3.1
    - gmp>=5.0.1,<7
    - cudatoolkit

build:
  number: {{ environ.get('TC_BUILD_NUMBER') }}
  skip: True   # [win]
  features:
    - tapir50

test:
  requires:
    - tapir50
  imports:
    - torch
    - torch.cuda
    - torch.utils
    - tensor_comprehensions
    - tensor_comprehensions.tc
    - tensor_comprehensions.autotuner
    - tensor_comprehensions.mapping_options

  source_files:
    - test_python

  commands:
    - test -f $PREFIX/lib/libtc_aten.so
    - test -f $PREFIX/lib/libtc_autotuner.so
    - test -f $PREFIX/lib/libtc_core.so
    - test -f $PREFIX/lib/libtc_lang.so
    - test -f $PREFIX/lib/libtc_proto.so

    - test -f $PREFIX/lib*/libgmock_main.a
    - test -f $PREFIX/lib*/libgmock.a
    - test -f $PREFIX/lib*/libgtest_main.a
    - test -f $PREFIX/lib*/libgtest.a

    - test -d $PREFIX/include/dlpack
    - test -d $PREFIX/include/gmock
    - test -d $PREFIX/include/gtest
    - test -d $PREFIX/include/cub

    - python test_python/test_tc.py -v
    - python test_python/test_tc_torch.py -v
    - python test_python/test_debug_init.py -v

about:
  home: https://github.com/nicolasvasilache/c2isl
  license: Apache 2.0
  summary: Framework-Agnostic Abstractions for High-Performance Machine Learning

extra:
  recipe-maintainers:
    - prigoyal
