package:
  name: tensor_comprehensions
  version: "{{ environ.get('TC_BUILD_VERSION') }}"

source:
  git_url: https://github.com/nicolasvasilache/c2isl.git
  git_rev: "{{ environ.get('TC_GIT_HASH') }}"

requirements:
  build:
    - isl-tc==0.2.1
    - llvm-tapir50==0.2.2
    - halide==0.2.2
    - gflags==2.4.4
    - glog==0.3.9
    - protobuf==3.4.1
    # we install pytorch since we want compatibility of TC with it for the release
    - pytorch==0.3.1
    - gmp>=5.0.1,<7
    - cmake
    - setuptools
    - pyyaml
    - cudatoolkit

  run:
    - isl-tc==0.2.1
    - llvm-tapir50==0.2.2
    - halide==0.2.2
    - gflags==2.4.4
    - glog==0.3.9
    - protobuf==3.4.1
    - pytorch==0.3.1
    - gmp>=5.0.1,<7
    - cudatoolkit

build:
  number: {{ environ.get('TC_BUILD_NUMBER') }}
  skip: True   # [win]

test:
  imports:
    - torch
    - torch.cuda
    - torch.utils
    - tensor_comprehensions
    - tensor_comprehensions.tc
    - tensor_comprehensions.autotuner
    - tensor_comprehensions.mapping_options

  source_files:
    - test_python

  commands:
    - test -f $PREFIX/lib/libtc_aten.so
    - test -f $PREFIX/lib/libtc_autotuner.so
    - test -f $PREFIX/lib/libtc_core.so
    - test -f $PREFIX/lib/libtc_lang.so
    - test -f $PREFIX/lib/libtc_proto.so

    - test -f $PREFIX/lib*/libgmock_main.a
    - test -f $PREFIX/lib*/libgmock.a
    - test -f $PREFIX/lib*/libgtest_main.a
    - test -f $PREFIX/lib*/libgtest.a

    - test -d $PREFIX/include/dlpack
    - test -d $PREFIX/include/gmock
    - test -d $PREFIX/include/gtest
    - test -d $PREFIX/include/cub

    - ./test_python/run_test.sh

about:
  home: https://github.com/facebookresearch/TensorComprehensions
  license: Apache 2.0
  summary: A domain specific language to express machine learning workloads

extra:
  recipe-maintainers:
    - prigoyal
